### ISSUE TITLE
Accourdance problem 

### ISSUE THREAD

**Issue by cagdasb** [khast3x/h8mail#112]
*Issues not respecting the issue template will be closed without being read, thank you.*

### Checkbox

- [x] I have thoroughly checked the answer is not in the [wiki](https://github.com/khast3x/h8mail/wiki).

### Env

* h8mail version: Version 2.5.4
* Python version: Python 3.8.3
* Operating System: Windows 10 

### Description
 
New problem is accordance. I want to find exact email on local databse instead of accordance emails. But - -loose not working 

### What I Did

```
H8mail - t target.txt - lb x/y/xxx.txt -sk - - loose



```

**Comment by khast3x** [comment]
Hello,

The `--loose` argument will only skip the enforced email pattern recognition, so you can search for just "@example.com" or "john.doe" instead of having to have "john.doe@example.com".   

Moreover h8mail will perform a pattern search when used locally, so if you're searching for "doe" with `--loose` it will find all names containing "doe" such as "john.doe", "jeff.doe". This is expected behavior.   

If you want to have more granular filtering on your results either use precise emails without `--loose`, or export the results as CSV with the `-o` and import them into Excel/Libreoffice Calc.

Hope this helps!

Cheers

**Comment by cagdasb** [comment]
> 
> 
> Hello,
> 
> The `--loose` argument will only skip the enforced email pattern recognition, so you can search for just "@example.com" or "john.doe" instead of having to have "[john.doe@example.com](mailto:john.doe@example.com)".
> 
> Moreover h8mail will perform a pattern search when used locally, so if you're searching for "doe" with `--loose` it will find all names containing "doe" such as "john.doe", "jeff.doe". This is expected behavior.
> 
> If you want to have more granular filtering on your results either use precise emails without `--loose`, or export the results as CSV with the `-o` and import them into Excel/Libreoffice Calc.
> 
> Hope this helps!
> 
> Cheers

Hello,
Thansk for your kind answer. I was having output with -o output.txt 

I will stop using --loose as you told. 
If I change all lines of target.txt name@domain.com to "name@domain.com" for example would it solve my problem?

It's really slow when I'm searching 1million emails. Is there a way to make it faster? Thank you.

**Comment by khast3x** [comment]
> If I change all lines of target.txt name@domain.com to "name@domain.com" for example would it solve my problem?

I don't think so, no. If the problem is from false pattern matching, h8mail will always look for globed patterns like [here](https://github.com/khast3x/h8mail/blob/master/h8mail/utils/localsearch.py#L64).  

> It's really slow when I'm searching 1million emails. Is there a way to make it faster? Thank you.

If you have many targets, split the target file and launch h8mail for each file. If you have a big file to search for results, split the big file and feed to h8mail, it will automatically multi-task searching.

Hope this helps
