### ISSUE TITLE
Error when executing the -gz flag.

### ISSUE THREAD

**Issue by sumgro** [khast3x/h8mail#26]
While executing the -gz flag with h8mail to scan the Collection#1 gzip file, it shows the results (may not be complete) and then always ends up with following error:
---------------------------
[!] Something went wrong with gzip worker
Compressed file ended before the end-of-stream marker was reached

 __________________________________________________________________________________________
 
[>] Showing results for <redacted>

[~] No results founds
__________________________________________________________________________________________

                                   Session Recap:  

                 Target                  |                   Status                  
__________________________________________________________________________________________

              <redacted>               |               Not Compromised              
__________________________________________________________________________________________

Execution time (seconds):   4769.6074821949005  

Done

**Comment by khast3x** [comment]
Hello,

It seems this happens when python cannot find where to stop reading inside the `.gz` file, which is due to either:  
* The file being corrupted when compressed
* The file being corrupted when downloaded
  * Download was not finished or interrupted

Typically, if you try to decompress the targeted Collection1 file, you should also maybe an error?
So things you can do if you're still having issues: check the md5 signature of the file you downloaded, and check if its matching.
Feel free to send me a magnetlink by mail if you want me to give it a try.

**Comment by khast3x** [comment]
Closing for lack of answer. Feel free to reopen if you're still having issues. Cheers
