### ISSUE TITLE
API Keys issue

### ISSUE THREAD

**Issue by Azrb** [khast3x/h8mail#37]
seems HIBP API Keys changed/stopped working..

[~] HIBP free tier will stop working on the 2019/08/18
[~] You can already use a purchased API key using h8mail (config file)
[!] Could not contact HIBP for xxx@xxx.com
401

**Comment by khast3x** [comment]
Hello,
Did you purchase an API key? If so, please be aware that they expire after 1 month.

Cheers

**Comment by randysix** [comment]
Hello @Azrb,
All along the solution to this issue was quite simple.
Try running:

**h8mail -t [query] -k "[Key]=[V]"** 

For example: 

**h8mail -t [query] -k "leak-lookup_pub=1bf94ff907f68d511de9a610a6ff9263"**

For more examples check the documentation.
If this doesn't work, generate a blank configuration file by adding _--gen-config_ or _-g_ to the command you wanna run. This will generate a _h8mail_config.ini_ file, and in that file activate your keys just like in the _config.ini_ file. 

Hope this works.

Thank you very much @khast3x for your help by the way. Kudos to you for your amazing project!

**Comment by khast3x** [comment]
Hello @randysix ,

Thank you for sharing your solution and helping out new users. Much appreciated!

Cheers!
