### ISSUE TITLE
It doesn't search anymore on scylla

### ISSUE THREAD

**Issue by DanieleCalzetti** [khast3x/h8mail#56]
* h8mail version: 2.5
* Python version: 3.7.6
* Operating System: Kali

### Description

I launched a scan with an email that I have previously tried. 
The first time H8mail checked in scylla.sh without a prior configuration, the second time that I tried with the same email It hasn't checked in scylla but only in emailrep.

### What I Did
I tried to remove the software and to install it another time and to run the software by using other email with the same results. 

The command that I ran:

         `h8mail -t <email>`

**Comment by khast3x** [comment]
Hello,

The owner of scylla.sh has recently decided to limit the usage of his service to pre-authorized users.  
h8mail should be updated soon to reflect these changes.  

Users wishing to access scylla.sh can request access by sending an email at `acaceres AT 0-sec.net` or a DM to [@_hyp3ri0n](https://twitter.com/_hyp3ri0n) on Twitter.  

Will close this issue when h8mail will be updated.

Cheers

**Comment by DanieleCalzetti** [comment]
Ok, thank you very much for the information.

**Comment by amartya89** [comment]
HI @khast3x ,

Indeed h8mail is an excellent OSINT and i am wholeheartedly thankful to you for this. But the saddest part is scylla.sh issue. Is there any way outs that we can use the same. I don't know if contacting the owner would help, as i have already contacted but no response. Any other open alternatives that can be used which is equivalent to scylla but open source? 

Also tried to reach you via DM but could not start conversation till now.

**Comment by khast3x** [comment]
Hello @amartya89, 
There is currently no free alternative, as scylla was used by infosec professionals but abused by a more toxic crowd, similar to HIBP.  
Everything else is documented [in the wiki](https://github.com/khast3x/h8mail/wiki/Using-APIs) regarding working alternatives.  
If you have no available funds you can download and compile your own databases, as h8mail can search those too, or use cloud services with docker [as described in the public blog post](https://khast3x.club/posts/2019-06-07-docker-h8mail/).   

*Notice to public: this issue is for tracking scylla's auth integration, further commenting needs to be about **code discussion or pull requests**. Thanks.*

Regards,

**Comment by amartya89** [comment]
Thanks @khast3x  for the detail. Would you please help in scylla's auth integration? Also to purchase the service, what is the way?

Since, i am blocked in DM, i can only ask you here.

Thanks.

**Comment by Blakeboy02** [comment]
Hi, sorry for my intrusiveness,

Do you possibly know around when this issue will be resolved (also does anybody know where to get users.tar.gz Adobe's 2013 leak??)

**Comment by khast3x** [comment]
Fixed with this release.  
Check the wiki for [update instructions](https://github.com/khast3x/h8mail/wiki/Install#update).  
Cheers
