### ISSUE TITLE
Still not working after 2 updates.

### ISSUE THREAD

**Issue by elazzzzyy** [khast3x/h8mail#70]
* h8mail version: 2.5.2 ROCKSMASSON.2
* Python version: 3.7
* Operating System: WSL

### Description
After a day or two of originally posting an issue about h8mail saying Scylla is down and a compromised email is not comprised after doing the upgrade command, You responded with "probably post update load stress". this was not the case and it still does not work after the Scylla fix and the emailrep fix giving me the same errors as before being that a compromised email is not compromised and that Scylla is down.

### What I Did

```
cd h8mail
h8mail -t email@example.com

output: 
[>] h8mail is up to date
[~] Removing duplicates
[>] Targets:
[>] example@email.com
[~] scylla.sh is down, skipping
[~] Target factory started for example@email.com
[~] [example@email.com]>[hunter.io public]
[>] Found 0 related emails for example@email.com using hunter.io (public)

 __________________________________________________________________________________________

[>] Showing results for  example@email.com

[~] No results founds
__________________________________________________________________________________________



                                   Session Recap:


                 Target                  |                   Status
__________________________________________________________________________________________

           example@email.com             |               Not Compromised
__________________________________________________________________________________________

Execution time (seconds):   0.5600109100341797
```

**Comment by khast3x** [comment]
Hello @elazzzzyy ,
h8mail issues are for h8mail related issues only.  
It seems your issue is with the data providers being down. I suggest you check with the service directly.  
That being said you are referring to scylla.sh which is a free project to help professionals. If you feel they have too much downtime you can always help by [donating here](https://www.buymeacoffee.com/Eiw47ImnT), especially regarding server maintenance costs.   

Otherwise, if scylla is up but h8mail says it is down, please check that you are not using a blacklisted IP or VPN by common providers.  

Finally if you feel there is still an issue with h8mail directly, please open a new issue with the ouput using `--debug`.

Cheers!
